In [3]:
import pandas as pd
import numpy as np

In [4]:
bf = pd.read_csv('bodyfat.csv')

In [5]:
bf.head()

Bodyfat  Age  Weight  Height  Neck  Chest  Abdomen  Ankle  Biceps  Wrist
0     32.3   41  247.25   73.50  42.1  117.0    115.6   26.3    37.3   19.7
1     22.5   31  177.25   71.50  36.2  101.1     92.4   24.6    30.1   18.2
2     22.0   42  156.25   69.00  35.5   97.8     86.0   24.0    31.2   17.4
3     12.3   23  154.25   67.75  36.2   93.1     85.2   21.9    32.0   17.1
4     20.5   46  177.00   70.00  37.2   99.7     95.6   22.5    29.1   17.7

In [6]:
bf.shape

(100, 10)

In [7]:
# BodyFat is the target variable.

In [8]:
bf.corr()

Bodyfat       Age    Weight    Height      Neck     Chest   Abdomen  \
Bodyfat  1.000000  0.255798  0.595959  0.032210  0.504443  0.682266  0.811593   
Age      0.255798  1.000000 -0.097905 -0.268673  0.038501  0.072908  0.141339   
Weight   0.595959 -0.097905  1.000000  0.568433  0.838977  0.916047  0.888317   
Height   0.032210 -0.268673  0.568433  1.000000  0.370396  0.345312  0.265403   
Neck     0.504443  0.038501  0.838977  0.370396  1.000000  0.789799  0.769086   
Chest    0.682266  0.072908  0.916047  0.345312  0.789799  1.000000  0.922728   
Abdomen  0.811593  0.141339  0.888317  0.265403  0.769086  0.922728  1.000000   
Ankle    0.387911 -0.073522  0.790388  0.454985  0.664068  0.700092  0.643211   
Biceps   0.418107 -0.079398  0.786266  0.435460  0.701067  0.730124  0.652148   
Wrist    0.373095  0.216315  0.755123  0.420928  0.777259  0.695795  0.672061   

            Ankle    Biceps     Wrist  
Bodyfat  0.387911  0.418107  0.373095  
Age     -0.073522 -0.079398  0.216315  
Weight   0.790388  0.786266  0.755123  
Height   0.454985  0.435460  0.420928  
Neck     0.664068  0.701067  0.777259  
Chest    0.700092  0.730124  0.695795  
Abdomen  0.643211  0.652148  0.672061  
Ankle    1.000000  0.650841  0.688320  
Biceps   0.650841  1.000000  0.630473  
Wrist    0.688320  0.630473  1.000000

In [9]:
bf.iloc[:,1:11:].corr()

Age    Weight    Height      Neck     Chest   Abdomen     Ankle  \
Age      1.000000 -0.097905 -0.268673  0.038501  0.072908  0.141339 -0.073522   
Weight  -0.097905  1.000000  0.568433  0.838977  0.916047  0.888317  0.790388   
Height  -0.268673  0.568433  1.000000  0.370396  0.345312  0.265403  0.454985   
Neck     0.038501  0.838977  0.370396  1.000000  0.789799  0.769086  0.664068   
Chest    0.072908  0.916047  0.345312  0.789799  1.000000  0.922728  0.700092   
Abdomen  0.141339  0.888317  0.265403  0.769086  0.922728  1.000000  0.643211   
Ankle   -0.073522  0.790388  0.454985  0.664068  0.700092  0.643211  1.000000   
Biceps  -0.079398  0.786266  0.435460  0.701067  0.730124  0.652148  0.650841   
Wrist    0.216315  0.755123  0.420928  0.777259  0.695795  0.672061  0.688320   

           Biceps     Wrist  
Age     -0.079398  0.216315  
Weight   0.786266  0.755123  
Height   0.435460  0.420928  
Neck     0.701067  0.777259  
Chest    0.730124  0.695795  
Abdomen  0.652148  0.672061  
Ankle    0.650841  0.688320  
Biceps   1.000000  0.630473  
Wrist    0.630473  1.000000

In [10]:
# lets compare our Linear Ridge and Lasoo

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

## Model Building

In [12]:
lin = LinearRegression()
ridge = Ridge()
lasso = Lasso()

In [13]:
bf_x = bf.iloc[:,1:11:]
bf_y = bf.iloc[:,0]

# Fit

In [14]:
lin.fit(bf_x, bf_y)
lin.score(bf_x, bf_y)

0.7574718145674211

In [15]:
ridge.fit(bf_x, bf_y)
ridge.score(bf_x, bf_y)

0.757443675387616

In [16]:
lasso.fit(bf_x, bf_y)
lasso.score(bf_x, bf_y)

0.7315521962084663

# Predict

In [17]:
pred_lin = lin.predict(bf_x)
pred_ridge = ridge.predict(bf_x)
pred_lasso = lasso.predict(bf_x)

# Finding coiefficent

In [18]:
lin.coef_

array([ 8.37793344e-02, -8.33221931e-02,  3.59322556e-02,  1.12299488e-03,
       -1.38741586e-01,  1.03274094e+00,  2.25942608e-01,  1.48276392e-01,
       -2.20339906e+00])

In [19]:
ridge.coef_

array([ 0.08163352, -0.08421588,  0.03312492, -0.01323566, -0.13683971,
        1.0327911 ,  0.20932576,  0.14674991, -2.12104621])

In [20]:
lasso.coef_

array([ 0.01459462, -0.13525194, -0.        , -0.        , -0.        ,
        0.96688777, -0.        ,  0.        , -0.        ])

In [21]:
# coef_df = pd.DataFrame({'Linear':lin.coef_, 'Ridge':ridge.coef_, 'Lasso':lasso.coef_})
coef_df = pd.DataFrame({"Features":bf_x.columns, "Linear":lin.coef_ , "Ridge" : ridge.coef_ , "Lasso" :lasso.coef_ })

coef_df

Features    Linear     Ridge     Lasso
0      Age  0.083779  0.081634  0.014595
1   Weight -0.083322 -0.084216 -0.135252
2   Height  0.035932  0.033125 -0.000000
3     Neck  0.001123 -0.013236 -0.000000
4    Chest -0.138742 -0.136840 -0.000000
5  Abdomen  1.032741  1.032791  0.966888
6    Ankle  0.225943  0.209326 -0.000000
7   Biceps  0.148276  0.146750  0.000000
8    Wrist -2.203399 -2.121046 -0.000000

# Finding MSE

In [25]:
error_linear = bf_y - pred_lin
MSE = np.mean(np.square(error_linear))
print('Mean Squared Error in Linear',MSE)

error_ridge = bf_y - pred_ridge
MSE = np.mean(np.square(error_ridge))
print('Mean Squared Error in Ridge',MSE)

error_lasso = bf_y - pred_lasso
MSE = np.mean(np.square(error_lasso))
print('Mean Squared Error in Lasso',MSE)

Mean Squared Error in Linear 15.392269321317324
Mean Squared Error in Ridge 15.394055199660782
Mean Squared Error in Lasso 17.03728120220529
